services: 
  api_model:
    build: .
    image: polish-equity-analytics_api:latest
    container_name: polish-equity-analytics_container
    ports: 
      - "8000:8000"
    restart: always
    environment:
      - APP_ENV=production